<?php if ($block->ifEnabled()): ?>

    <div id="modal-content">
        <img src="https://cdn2.bigcommerce.com/n-biq04i/x44wvls/product_images/uploaded_images/wg-dj-size-guide-chart-2017.png?t=1508389147">
    </div>

    <div class="sizechart_wrapper" id="sizechart-popup-button">
        <a href="#"
           class="action_sizechart"
           id="sizechart-button"
           data-mage-init='{"popup-modal": {"target": "#modal-content"}}'>
            Size Chart
        </a>
    </div>

<?php endif; ?>

